//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCompCatalogueApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cour
    {
        public Cour()
        {
            this.CursusCours = new HashSet<CursusCour>();
            this.CourDates = new HashSet<CourDate>();
        }
    
        public long C_id { get; set; }
        public string Code { get; set; }
        public string Intitule { get; set; }
        public string Duree { get; set; }
        public string Niveau { get; set; }
        public string Annee { get; set; }
        public string Description { get; set; }
        public long CategorieID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<CursusCour> CursusCours { get; set; }
        public virtual ICollection<CourDate> CourDates { get; set; }
    }
}
