//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCompCatalogueApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CursusCour
    {
        public long C_id { get; set; }
        public long CursusID { get; set; }
        public long CourID { get; set; }
        public long Ordre { get; set; }
        public string Recommandation { get; set; }
    
        public virtual Cour Cour { get; set; }
        public virtual Cursu Cursu { get; set; }
    }
}
