//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCompCatalogueApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ITCompTrainingDBEntities1 : DbContext
    {
        public ITCompTrainingDBEntities1()
            : base("name=ITCompTrainingDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Cour> Cours { get; set; }
        public virtual DbSet<Cursu> Cursus { get; set; }
        public virtual DbSet<CursusCour> CursusCours { get; set; }
        public virtual DbSet<Technology> Technologies { get; set; }
        public virtual DbSet<CourDate> CourDates { get; set; }
    }
}
